apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-05-09T13:25:16Z"
  generation: 1
  labels:
    app: dashboard
  name: dashboard
  namespace: dashboard
  resourceVersion: "130894"
  uid: 21f4df02-f3c9-4934-a715-574705c0def1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dashboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dashboard
    spec:
      containers:
      - image: rafay7655/dashboard:latest
        imagePullPolicy: Always
        name: dashboard
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-05-09T13:25:36Z"
    lastUpdateTime: "2023-05-09T13:25:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-05-09T13:25:16Z"
    lastUpdateTime: "2023-05-09T13:25:36Z"
    message: ReplicaSet "dashboard-5b6b874f79" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
